# Generated by Django 4.1.7 on 2023-04-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rentitems_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentitems',
            old_name='user_id',
            new_name='user',
        ),
    ]
