# Generated by Django 4.1.7 on 2023-04-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_rentitems_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('person_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_status', models.CharField(default='AVAILABLE', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RentItems',
        ),
    ]
