# Generated by Django 4.1.7 on 2023-04-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ratings',
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='distance',
            field=models.FloatField(),
        ),
    ]
