# Generated by Django 4.1.7 on 2023-04-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_car_brand_alter_car_category_alter_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='distance',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
